---
- name: "Get list of files inside {{ filetree_controller_credential_input_sources }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_credential_input_sources }}"
    file_type: file
    recurse: true
  register: __list_files_controller_credential_input_sources

- name: "Read Credential Input Sources definitions"
  ansible.builtin.include_vars:
    file: "{{ item.path }}"
  loop: "{{ __list_files_controller_credential_input_sources.files }}"
  register: __contents_filetree_controller_credential_input_sources

- name: "Populate Credential Input Sources list"
  ansible.builtin.set_fact:
    __populate_controller_credential_input_sources: "{{ (__populate_controller_credential_input_sources | default([])) + item.ansible_facts.controller_credential_input_sources }}"
  loop: "{{ __contents_filetree_controller_credential_input_sources.results }}"
  when: __contents_filetree_controller_credential_input_sources.results is defined and item.ansible_facts.controller_credential_input_sources is defined

- name: "Set Credential Input Sources Data Structure"
  ansible.builtin.set_fact:
    controller_credential_input_sources: "{{ __populate_controller_credential_input_sources }}"
  when: __populate_controller_credential_input_sources is defined
...
