---
- name: "Get list of files inside {{ filetree_controller_roles }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_roles }}"
    file_type: file
    recurse: true
  register: __list_files_controller_roles

- name: "Read Roles definitions"
  ansible.builtin.include_vars:
    file: "{{ item.path }}"
  loop: "{{ __list_files_controller_roles.files }}"
  register: __contents_filetree_controller_roles

- name: "Populate Roles list"
  ansible.builtin.set_fact:
    __populate_controller_roles: "{{ (__populate_controller_roles | default([])) + item.ansible_facts.controller_roles }}"
  loop: "{{ __contents_filetree_controller_roles.results }}"
  when: __contents_filetree_controller_roles.results is defined and item.ansible_facts.controller_roles is defined

- name: "Set Roles Data Structure"
  ansible.builtin.set_fact:
    controller_roles: "{{ __populate_controller_roles }}"
  when: __populate_controller_roles is defined
...
