---
- name: "Get list of files inside {{ filetree_controller_user_accounts }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_user_accounts }}"
    file_type: file
    recurse: true
  register: __list_files_controller_user_accounts

- name: "Read User Accounts definitions"
  ansible.builtin.include_vars:
    file: "{{ item.path }}"
  loop: "{{ __list_files_controller_user_accounts.files }}"
  register: __contents_filetree_controller_user_accounts

- name: "Populate User Accounts list"
  ansible.builtin.set_fact:
    __populate_controller_user_accounts: "{{ (__populate_controller_user_accounts | default([])) + item.ansible_facts.controller_user_accounts }}"
  loop: "{{ __contents_filetree_controller_user_accounts.results }}"
  when: __contents_filetree_controller_user_accounts.results is defined and item.ansible_facts.controller_user_accounts is defined

- name: "Set User Accounts Data Structure"
  ansible.builtin.set_fact:
    controller_user_accounts: "{{ __populate_controller_user_accounts }}"
  when: __populate_controller_user_accounts is defined
...
