---
controller_validate_certs: false
controller_license:
  manifest: manifest.zip
controller_password: '$encrypted'
controller_username: 'svc-admin'
controller_settings:
  - name: AUTH_LDAP_BIND_DN
    value: 'CN=svc-ansible,CN=Users,DC=example,DC=com'
  - name: AUTH_LDAP_SERVER_URI
    value: ldap://ipa1.example.com:389
  - name: AUTH_LDAP_BIND_PASSWORD
    value: "$encrypted"
  - name: AUTH_LDAP_GROUP_TYPE_PARAMS
    value: '{"name_attr": "cn", "member_attr": "uniqueMember"}'
  - name: AUTH_LDAP_GROUP_SEARCH
    value: '["DC=example,DC=com", "SCOPE_SUBTREE", "(objectClass=groupOfUniqueNames)"]'
  - name: AUTH_LDAP_GROUP_TYPE
    value: "MemberDNGroupType"
  - name: AUTH_LDAP_USER_DN_TEMPLATE
    value: "uid=%(user)s,CN=Users,DC=example,DC=com"
  - name: LOG_AGGREGATOR_HOST
    value: "https://10.0.0.10"
  - name: LOG_AGGREGATOR_PORT
    value: "9600"
  - name: LOG_AGGREGATOR_TYPE
    value: logstash
#  - name: LOG_AGGREGATOR_USERNAME
#    value: root
#    -name: LOG_AGGREGATOR_PASSWORD
#     value: "$encrypted$"
  - name: LOG_AGGREGATOR_LOGGERS
    value:
      - awx
      - activity_stream
      - job_events
      - system_tracking
  - name: LOG_AGGREGATOR_INDIVIDUAL_FACTS
    value: false
  - name: LOG_AGGREGATOR_ENABLED
    value: true

controller_organizations:
- name: FunkyTown
  description: This is the Default org for all FunkyTown members
- name: Admins
  description: This is the Admins org for those that manage tower
- name: Developers
  description: This is the Developers org for FunkyTown's developers.

controller_teams:
- name: DevX
  description: Developers working on applicaiton X
  organization: Developers
- name: DevX
  organization: Developers
  description: Developers working on application Y
- name: QA
  description: QA testers
  organization: FunkyTown
- name: ConsumersX
  description: End users for application X
  organization: FunkyTown
- name: Admins
  description: Ansible Automation Platform Admins
  organization: Admins


controller_roles:
- team: ConsumersX
  organization: FunkyTown
  role: execute
- team: DevX
  organization: Developers
  role: execute
