download_url: https://galaxy.ansible.com/download/redhat_cop-ee_utilities-2.0.1.tar.gz
format_version: 1.0.0
name: ee_utilities
namespace: redhat_cop
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.1
version_url: https://galaxy.ansible.com/api/v2/collections/redhat_cop/ee_utilities/versions/2.0.1/
